### ISSUE TITLE
Implement negation pseudo-class

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/braille-css#8]
AKA the :not() selector. See http://www.w3.org/TR/css3-selectors/#negation

**Comment by dkager** [comment]
This looks useful for snaekobbi/pipeline-mod-dedicon#11.

**Comment by bertfrees** [comment]
Not needed anymore for NLB.

**Comment by dkager** [comment]
Nor for Dedicon I think.

**Comment by bertfrees** [comment]
Fixed by https://github.com/snaekobbi/braille-css/commit/5b212e879d84c37d861ffcd231e7782fe61ba21d
